sw/blog/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^$', views.index, name='index'),

	#post board
	url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
	url(r'^post_new/$', views.post_new , name='post_new'),
	
	url(r'^(?P<post_pk>\d+)/comment/new/$', views.comment_new, name='comment_new'),
	url(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)edit/$', views.comment_edit, name='comment_edit'),
	url(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)delete/$', views.comment_delete, name='comment_delete'),

	# call board
	url(r'^call_new/$',views.call_new, name='call_new'),
	url(r'^(?P<pk>\d+)/call/$',views.call_detail, name='call_detail'),
	url(r'^(?P<call_pk>\d+)/call_comment/new/$', views.call_comment_new, name='call_comment_new'),
	url(r'^(?P<call_pk>\d+)/call_comment/(?P<pk>\d+)edit/$', views.call_comment_edit, name='call_comment_edit'),
	url(r'^(?P<call_pk>\d+)/call__comment/(?P<pk>\d+)delete/$', views.call_comment_delete, name='call_comment_delete'),

	#question board
	url(r'^question_new/$',views.question_new, name='question_new'),
	url(r'^(?P<pk>\d+)/question/$',views.question_detail, name='question_detail'),
	url(r'^(?P<question_pk>\d+)/question_comment/new/$', views.question_comment_new, name='question_comment_new'),
	url(r'^(?P<question_pk>\d+)/question_comment/(?P<pk>\d+)edit/$', views.question_comment_edit, name='question_comment_edit'),
	url(r'^(?P<question_pk>\d+)/question_comment/(?P<pk>\d+)delete/$', views.question_comment_delete, name='question_comment_delete'),

	#upload
	url(r'^upload_new/$',views.upload_new, name='upload_new'),
	url(r'^(?P<pk>\d+)/upload/$',views.upload_detail, name='upload_detail'),

]

sw/sw/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/',include('blog.urls',namespace='blog')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sw/blog/models.py
import os
from django import forms
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models

class Post(models.Model):
	title = models.CharField(max_length=100)
	content= models.TextField()
	photo = models.ImageField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering =['-id']

	def __str__(self):
		return self.title
# This is for free bulletin board.

class Comment(models.Model):
	post = models.ForeignKey(Post)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	message = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering =['-id']

	def get_edit_url(self):
		return reverse('blog:comment_edit', args=[self.post.pk, self.pk])

	def get_delete_url(self):
		return reverse('blog:comment_delete', args=[self.post.pk, self.pk])
# This is for the reply of free bulletin board.

class Question(models.Model):
    title = models.CharField(max_length=30)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
    	ordering=['id']
# This is for Q&A board

class question_Comment(models.Model):
	question = models.ForeignKey(Question)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	message = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def get_question_edit_url(self):
		return reverse('blog:question_comment_edit', args=[self.question.pk, self.pk])

	def get_question_delete_url(self):
		return reverse('blog:question_comment_delete', args=[self.question.pk, self.pk])

# This is for the reply of Q&A board

class Call(models.Model):
    title = models.CharField(max_length=30)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
    	ordering=['id']

# This is for request board

class call_Comment(models.Model):
	call = models.ForeignKey(Call)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	message = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def get_call_edit_url(self):
		return reverse('blog:call_comment_edit', args=[self.call.pk, self.pk])

	def get_call_delete_url(self):
		return reverse('blog:call_comment_delete', args=[self.call.pk, self.pk])
# This is for the reply of request board

class Upload(models.Model):
	photo = models.FileField()

	class Meta:
		ordering=['-id']
# This is for implementing uploading pixel file

class Search(models.Model):
	title = models.CharField(max_length=30)
	font_file = models.CharField(max_length = 100)

class Font(models.Model):
	title = models.CharField(max_length=100)
	font = models.FileField()

	class Meta:
		ordering=['-id']

 

# Create your models here.

sw/blog/forms.py
from django import forms
from .models import Comment, Post, Question, Call , Upload ,question_Comment , call_Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['message']

class QuestionCommentForm(forms.ModelForm):
	class Meta:
		model = question_Comment
		fields = ['message']

class CallCommentForm(forms.ModelForm):
	class Meta:
		model = call_Comment
		fields = ['message']

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			'title',
			'content',
		]

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = [
			'title',
			'contents',
		]

class CallForm(forms.ModelForm):
	class Meta:
		model = Call
		fields = [
			'title',
			'contents',
		]

class UploadForm(forms.ModelForm):
	class Meta:
		model = Upload
		fields = ['photo',]

sw/blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Comment ,Question , Call , Upload ,call_Comment , question_Comment , Search , Font
from .forms import CommentForm, PostForm , CallForm, QuestionForm , UploadForm , QuestionCommentForm , CallCommentForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .extracting_existing_fonts import estand, eflatten, econversion
from .font_similarity  import stand, flatten, conversion, jacsim




def index(request):
	post_list = Post.objects.all()
	question_list = Question.objects.all()
	call_list = Call.objects.all()
	search_list = Search.objects.all()
	upload_list = Upload.objects.all()

	#Search function
	query = request.GET.get("q")
	if query:
		search_list = search_list.filter(title__icontains=query)


	return render(request, 'blog/post_list.html', {
		'post_list' : post_list,
		'question_list':question_list,
		'call_list':call_list,
		'search_list':search_list,
		'upload_list':upload_list,

	})

def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {
			'post' : post,
		})

def question_detail(request, pk):
	question = get_object_or_404(Question, pk=pk)
	return render(request, 'blog/question_detail.html', {
			'question' : question,
		})

def call_detail(request, pk):
	call = get_object_or_404(Call, pk=pk)
	return render(request, 'blog/call_detail.html', {
			'call' : call,
		})


def upload_detail(request, pk):
	upload = get_object_or_404(Upload, pk=pk)
	font_list = Font.objects.all()
	upload_font = conversion(upload.photo.path)
	stored_font = []
	
	for efont in font_list:
		stored_font.append({
			"title": efont.title,
			"similarity": jacsim(upload_font, econversion(efont.font.path))	
		})
	
	
	return render(request, 'blog/upload_detail.html', {
			'upload' : upload, 'sf' : stored_font,  

	})
# Whole Function upload_detail is the responsible of Semin Han


@login_required
def post_new(request):
	if request.method=="POST":
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			form = form.save(commit=False)
			form.save()
			return redirect('blog:post_detail' , form.pk)
	else:
		form = PostForm()
	return render(request, "blog/post_form.html",{
		"form":form,
		})
	

@login_required
def comment_new(request, post_pk):
	post = get_object_or_404(Post, pk = post_pk)

	if request.method =='POST':
		form = CommentForm(request.POST, request.FILES)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.author = request.user
			comment.save()
			return redirect('blog:post_detail', post.pk)
	else:
		form = CommentForm()
	return render(request, 'blog/comment_form.html', {
			'form':form,
		})

@login_required
def comment_edit(request, post_pk, pk):
	comment = get_object_or_404(Comment, pk=pk)
	if comment.author != request.user:
		return redirect('blog:post_detail', post_pk)

	if request.method =='POST':
		form = CommentForm(request.POST, request.FILES, instance=comment)
		if form.is_valid():
			comment = form.save()
			return redirect('blog:post_detail', post_pk)
	else:
		form = CommentForm(instance=comment)
	return render(request, 'blog/comment_form.html', {
			'form':form,
		})

@login_required
def comment_delete(request, post_pk, pk):
	comment = get_object_or_404(Comment, pk=pk)
	if comment.author != request.user:
		return redirect('blog:post_detail', post_pk)

	if request.method =='POST':
		comment.delete()
		return redirect('blog:post_detail', post_pk)

	return render(request, 'blog/comment_confirm_delete.html', {
			'comment': comment,
	})



@login_required
def question_new(request):
	if request.method=="POST":
		form = QuestionForm(request.POST, request.FILES)
		if form.is_valid():
			form = form.save(commit=False)
			form.save()
			return redirect('blog:question_detail' , form.pk)
	else:
		form = QuestionForm()
	return render(request, "blog/question_form.html",{
		"form":form,
		})

@login_required
def question_comment_new(request, question_pk):
	question = get_object_or_404(Question, pk = question_pk)

	if request.method =='POST':
		form = QuestionCommentForm(request.POST, request.FILES)
		if form.is_valid():
			question_comment = form.save(commit=False)
			question_comment.question = question
			question_comment.author = request.user
			question_comment.save()
			return redirect('blog:question_detail', question.pk)
	else:
		form = QuestionCommentForm()
	return render(request, 'blog/question_comment_form.html', {
			'form':form,
		})


@login_required
def question_comment_edit(request, question_pk, pk):
	question_comment= get_object_or_404(question_Comment, pk=pk)
	if question_comment.author != request.user:
		return redirect('blog:question_detail', question_pk)

	if request.method =='POST':
		form = QuestionCommentForm(request.POST, request.FILES, instance=question_comment)
		if form.is_valid():
			comment = form.save()
			return redirect('blog:question_detail', question_pk)
	else:
		form = QuestionCommentForm(instance=question_comment)
	return render(request, 'blog/question_comment_form.html', {
			'form':form,
		})

@login_required
def question_comment_delete(request, question_pk, pk):
	question_comment = get_object_or_404(question_Comment, pk=pk)
	if question_comment.author != request.user:
		return redirect('blog:question_detail', question_pk)

	if request.method =='POST':
		question_comment.delete()
		return redirect('blog:question_detail', question_pk)

	return render(request, 'blog/comment_confirm_delete.html', {
			'question_comment': question_comment,
	})

@login_required
def call_new(request):
	if request.method=="POST":
		form = CallForm(request.POST, request.FILES)
		if form.is_valid():
			form = form.save(commit=False)
			form.save()
			return redirect('blog:call_detail' , form.pk)
	else:
		form = CallForm()
	return render(request, "blog/call_form.html",{
		"form":form,
		})

@login_required
def call_comment_new(request, call_pk):
	call = get_object_or_404(Call, pk = call_pk)

	if request.method =='POST':
		form = CallCommentForm(request.POST, request.FILES)
		if form.is_valid():
			call_comment = form.save(commit=False)
			call_comment.call = call
			call_comment.author = request.user
			call_comment.save()
			return redirect('blog:call_detail', call.pk)
	else:
		form = CallCommentForm()
	return render(request, 'blog/call_comment_form.html', {
			'form':form,
		})


@login_required
def call_comment_edit(request, call_pk, pk):
	call_comment = get_object_or_404(call_Comment, pk=pk)
	if call_comment.author != request.user:
		return redirect('blog:call_detail',call_pk)

	if request.method =='POST':
		form = CommentForm(request.POST, request.FILES, instance=call_comment)
		if form.is_valid():
			call_comment = form.save()
			return redirect('blog:call_detail',call_pk)
	else:
		form = CommentForm(instance=call_comment)
	return render(request, 'blog/comment_form.html', {
			'form':form,
		})

@login_required
def call_comment_delete(request, call_pk, pk):
	call_comment = get_object_or_404(call_Comment, pk=pk)
	if call_comment.author != request.user:
		return redirect('blog:call_detail',call_pk)

	if request.method =='POST':
		call_comment.delete()
		return redirect('blog:call_detail',call_pk)

	return render(request, 'blog/comment_confirm_delete.html', {
			'call_comment': call_comment,
	})

@login_required
def upload_new(request):
	if request.method=="POST":
		form = UploadForm(request.POST, request.FILES)
		if form.is_valid():
			form = form.save(commit=False)
			form.save()
			return redirect('blog:upload_detail', form.pk)
	else:
		form = UploadForm()
	return render(request, "blog/upload_form.html",{
		"form":form,
		})



#파일 업로드

# Create your views here.

sw/blog/templates/blog/call_detail.html
{% extends "accounts/layout.html" %}
{% block title %}{{ call.title }}{% endblock %}

{% block content %}
<h1>{{ call.title }}</h1>

{% if call.photo %}
	<img src="{{ call.photo.url }}" />
{% endif %}
<hr />

{{ call.contents|linebreaks }}

<hr/>
<center><h2>댓글</h2></center>
{% for call_comment in call.call_comment_set.all %}
	<center><li>
		{{ call_comment.message }}<br />
		by {{ call_comment.author }} 
		at {{ call_comment.created_at }}<br/>
		<a href="{{ call_comment.get_call_edit_url }}">
		수정
		</a>
		<a href="{{ call_comment.get_call_delete_url }}">
			삭제
		</a>
	</li></center>
{% endfor %}
<hr />
<a href="{% url "blog:index" %}" class="btn btn-primary">목록으로</a>
<a href="{% url "blog:call_comment_new" call.pk %}"  class="btn btn-primary">댓글쓰기</a>
{% endblock 

<!-- Developed by Jihoon Kim -->

sw/blog/templates/blog/post_detail.html
{% extends "accounts/layout.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>

{% if post.photo %}
	<img src="{{ post.photo.url }}" />
{% endif %}
<hr />

{{ post.content|linebreaks }}

<hr/>
<center><h2>댓글</h2></center>
{% for comment in post.comment_set.all %}
	<center><li>
		{{ comment.message }}<br />
		by {{ comment.author }} 
		at {{ comment.created_at }}<br/>
		<a href="{{ comment.get_edit_url }}">
		수정
		</a>
		<a href="{{ comment.get_delete_url }}">
			삭제
		</a>
	</li></center>
{% endfor %}
<hr />
<a href="{% url "blog:index" %}" class="btn btn-primary">목록으로</a>
<a href="{% url "blog:comment_new" post.pk %}"  class="btn btn-primary">댓글쓰기</a>
{% endblock %}
<!-- Developed by GweonHo Jung -->

sw/blog/templates/blog/post_list.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html>
	<head>
		<title>FonTastic</title>
		<meta charset="UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}"/>
		<noscript><link rel="stylesheet" type="text/css" href="assets/css/noscript.css" /></noscript>	
		<style>
		tr, td {
			font-family: "Source Sans Pro", Helvetica, sans-serif;
			font-size: 0.8rem;
			font-weight: 900;
			letter-spacing: 0.075em;
			line-height: 1.5;
			padding: 0 0.75rem 0.75rem 0.75rem;
			text-align: left;
			text-transform: uppercase;
		}
		</style>
	</head>

	<body class = "is-loading">
		{% block content %}
		<div id = "wrapper" class = "fade-in">
			<!--INTRO-->
			<div id = "intro">
				<h1>F O N T A S T I C</h1>
				<p>In Fontastic, You can find font you want by image. </p>
				<ul class = "actions">
					<li><a href ="#header" class = "button icon solo fa-arrow-down scrolly">Continue</a></li>
				</ul>
			</div>

		<!--Header-->
			<header id = "header">
				<a href= "#" class = "logo">FONTASTIC</a>
			</header>

			<nav id = "nav">
				<ul class = "links">
					<li class="actions"><a href ="#search_font" class="scrolly">SEARCH FONT<a></li>
					<li class="actions"><a href ="#find_font" class="scrolly">FIND FONT</a></li>
					<li class="actions"><a href ="#board" class="scrolly">BOARD</a></li>
					<li class="actions"><a href ="#Q_A" class="scrolly">Q&A</a></li>
					<li class="actions"><a href ="#request" class="scrolly">REQUEST</a></li>
					<li class="actions"><a href="#directions" class="scrolly">How to use?</a></li>
					{% if not user.is_authenticated %}
          		<li><a href="{% url "login" %}?next={{ request.path }}">Login</a></li>
          		<li><a href="{% url "signup" %}">Signup</a></li>
          	{% else %}
          		<li><a href="{% url "logout" %}?next={{ request.path }}">Logout</a></li>
          		<li><a href="{% url "profile" %}">Profile</a></li>
          	{% endif %}
				</ul>
				
			</nav>
		<!--main-->
			<div id = "main">
				<!--search font-->
				<div id ="search_font">
					<h2>SEARCH FONT</h2><br/>
					
					<table border ="1" cellspacing="0" summray="Search">
						<colgroup>
							<col width="150">
							<col width="300">
						</colgroup>
						<thead>
						<tr>
							<th>Font Name</th>
							<th>Font Download</th>
						</tr>
						</thead>
						<tbody>
							{% for search in search_list %}<tr>
							<td class="title_board" style="padding-left:30px;">
								<a href="#">{{ search.title }}</a>
							</td>
							<td style="padding-left:30px;">
								<a href="#">{{ search.font_file}}</a>
							</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
					<br/>
					<form emthod='GET' action=''>
					<input type="text" name="q" placeholder='Search fonts' />
					<input type='submit' value='Search'/>
					</form>
				</div>
			
			<!--find font-->
				<div id="find_font">
					<h2>FIND FONT</h2>
						<center><button><a href="{% url "blog:upload_new" %}" class="actions">UPLOAD</a></button></center>
					
				</div>
			
			<!--board-->
			<div id="section">
				<div id ="board">
					<h2>BOARD | <span><a href ="#nav" class="actions scrolly">MENU</a></span></h2>
					<table border = "1" cellspacing ="0" summary="게시판">
						<colgroup>
						<col width="150">
						<col width="200">
						<col width="80">
						<col width="70">
					</colgroup>
					<thead>
						<tr>
							<th scope="col">제목</th>
							<th scope="col">내용</th>
							<th scope="col">날짜</th>
							<th scope="col">댓글</th>
						</tr>
					</thead>
					<tbody>
						{% for post in post_list %}
						<tr class="reply_borad">
							<td class="title_board" style="padding-left:30px;">
								<a href="{% url "blog:post_detail" post.pk%}">{{ post.title }}</a>
							</td>
							<td class="name_board"><a href="{% url "blog:post_detail" post.pk %}">{{ post.content|linebreaks }}
								{% for comment in post.comment_set.all %}
								<li>
								{{ comment.message }}<br />
								by {{ comment.author }}<br />
								at {{ comment.created_at }}
								<a href="{{ comment.get_edit_url }}">
									수정
								</a>
								<a href="{{ comment.get_delete_url }}">
									삭제
								</a>
								</li>
								{% endfor %}</a>
							</td>
							<td class="date_board"><a href="#"><li>{{ post.created_at }}</li></a>
							</td>
							<td><a href="{% url "blog:comment_new" post.pk %}"  class="logo">댓글쓰기</a>
							</td>
							{% endfor %}
							
						</tr>
						<tr>
							<td>
								<button><a href="{% url "blog:post_new" %}"  class="logo">글쓰기</a></button>
							</td>
						</tr>
						
					
						
						
							
						
						
					</tbody>
					</table>
				</div>

			<!--Q&A-->

				<div id="Q_A">
					<h2>Q&A | <span><a href ="#nav" class="actions scrolly">MENU</a></span></h2>
					<table border = "1" cellspacing ="0" summary="게시판">
						<colgroup>
						<col width="150">
						<col width="200">
						<col width="80">
						<col width="70">
					</colgroup>
					<thead>
						<tr>
							<th scope="col">제목</th>
							<th scope="col">내용</th>
							<th scope="col">날짜</th>
							<th scope="col">댓글</th>
						</tr>
					</thead>
					<tbody>
						{% for question in question_list %}
						<tr class="reply_borad">
							<td class="title_board" style="padding-left:30px;">
								<a href="{% url "blog:question_detail" question.pk %}">{{ question.title }}</a>
							</td>
							<td class="name_board"><a href="{% url "blog:question_detail" question.pk %}">{{ question.contents|linebreaks }}
								{% for question_comment in question.question_comment_set.all %}
									<li>{{ question_comment.message }}<br />
										by {{ question_comment.author }}<br />
										at {{ question_comment.created_at }}
									<a href="{{ question_comment.get_question_edit_url }}">
									수정
								</a>
							<a href="{{ question_comment.get_question_delete_url }}">
									삭제
								</a></li>
								{% endfor %}</a>
							</td>
							<td class="date_board"><a href="#">{{ question.created_at }}</a>
							</td>
							<td><a href="{% url "blog:question_comment_new" question.pk %}"  class="logo">댓글쓰기</a>
							</td>
							{% endfor %}
						
						</tr>
						<tr>
							<td>
								<button><a href="{% url "blog:question_new" %}"  class="logo">글쓰기</a></button>
							</td>
						</tr>
						
						
						
					</tbody>
					</table>
				
					
				</div>
			
			<!--request-->
				<div id="request">
					<h2>REQUEST | <span><a href ="#nav" class="actions scrolly">MENU</a></span></h2>
					<table border = "1" cellspacing ="0" summary="게시판">
						<colgroup>
						<col width="150">
						<col width="200">
						<col width="80">
						<col width="70">
					</colgroup>
					<thead>
						<tr>
							<th scope="col">제목</th>
							<th scope="col">내용</th>
							<th scope="col">날짜</th>
							<th scope="col">댓글</th>
						</tr>
					</thead>
					<tbody>
						{% for call in call_list %}
						<tr class="reply_borad">
							<td class="title_board" style="padding-left:30px;">
								<a href="{% url "blog:call_detail" call.pk%}">{{ call.title }}</a>
							</td>
							<td class="name_board"><a href="{% url "blog:call_detail" call.pk %}">{{ call.contents|linebreaks }}
								{% for call_comment in call.call_comment_set.all %}
									<li>{{ call_comment.message }}<br />
										by {{ call_comment.author }}<br/>
										at {{ call_comment.created_at }}
									<a href="{{ call_comment.get_call_edit_url }}">
									수정
								</a>
								<a href="{{ call_comment.get_call_delete_url}}">
									삭제
								</a>
							</li>
								{% endfor %}</a>
							</td>
							<td class="date_board"><a href="#">{{ call.created_at }}</a>
							</td>
							<td><a href="{% url "blog:call_comment_new" call.pk %}" class="logo">댓글쓰기</a>
							</td>
							{% endfor %}
							

						</tr>
						<tr>
							<td>
								<button><a href="{% url "blog:call_new" %}" class="logo">글쓰기</a></button>
							</td>
						</tr>
						
						
					</tbody>
					</table>
				</div>
				<div id="directions">
		<h2>How to use? | <span><a href ="#nav" class="actions scrolly">MENU</a></span></h2>
		<table>
			<colgroup>
				<col width="150">
				<col width="350">
			</colgroup>
			<thead>
				<th scope="col">순서</th>
				<th scope="col">내용</th>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>imageJ <a href="#">다운로드</a></td>
				</tr>
				<tr>
					<td>2</td>
					<td>
						실행시킨 후 다음 사진을 따라해주세요<br/>
						<img src="..\..\static\images\2_1.png" width="500" height="300">
						<br/>
						<img src="..\..\static\images\2_2.png" width="500" height="300"><br/>
						<br/>
						<img src="..\..\static\images\2_3.png" width="500" height="300">
						<br/>
						<img src="..\..\static\images\2_4.png" width="500" height="300"><br/>
						
					</td>
				</tr>
				<tr>
					<td>3</td>
					<td>저장한 픽셀 파일을 Find Font에서 UPLOAD 해주세요</td>
				</tr>
			</tbody>
		</table>
	</div>
			</div>
		</div>
	</div>
	
		{% endblock %}
	
	<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'js/skel.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>
<!-- Developed by GweonHo Jung -->


		
	</body>	
</html>

sw/blog/templates/blog/question_detail.html
{% extends "accounts/layout.html" %}
{% block title %}{{ question.title }}{% endblock %}

{% block content %}
<h1>{{ question.title }}</h1>

{% if question.photo %}
	<img src="{{ question.photo.url }}" />
{% endif %}
<hr />

{{ question.contents|linebreaks }}

<hr/>
<center><h2>댓글</h2></center>
{% for question_comment in question.question_comment_set.all %}
	<center><li>
		{{ question_comment.message }}<br />
		by {{ question_comment.author }} 
		at {{ question_comment.created_at }}<br/>
		<a href="{{ question_comment.get_question_edit_url }}">
		수정
		</a>
		<a href="{{ question_comment.get_question_delete_url }}">
			삭제
		</a>
	</li></center>
{% endfor %}
<hr />
<a href="{% url "blog:index" %}" class="btn btn-primary">목록으로</a>
<a href="{% url "blog:question_comment_new" question.pk %}"  class="btn btn-primary">댓글쓰기</a>
{% endblock %}
<!-- Developed by GweonHo Jung -->